name: Publish
on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * 4

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo "hello" > /tmp/a.txt
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/a.txt
        asset_name: mything
        tag: version1
        release_name: aa 
        overwrite: true
        file_glob: true
